export const Checkbox = {
  formControl_root: {},
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  formLabel_root: {},
  formLabel_focused: {},
  formLabel_error: {},
  formLabel_disabled: {},
  checkbox_root: {},
  checkbox_checked: {},
  checkbox_disabled: {},
  checkbox_colorPrimary: {},
  checkbox_colorSecondary: {},
};

export const CheckboxGroup = {
  formLabel_root: {},
  formLabel_focused: {},
  formLabel_error: {},
  formLabel_disabled: {},
  formGroup_root: {},
  formGroup_row: {},
};

export const MessageDialog = {
  dialog_root: {},
  dialog_paper: {},
  dialog_paperWidthXs: {},
  dialog_paperWidthSm: {},
  dialog_paperWidthMd: {},
  dialog_paperFullWidth: {},
  dialog_paperFullScreen: {},
  dialogTitle_root: {},
  dialogContent_root: {},
  dialogActions_root: {},
  dialogActions_action: {},
};

export const Radio = {
  formControlLabel_root: {},
  formControlLabel_disabled: {},
  formControlLabel_label: {},
  radio_root: {},
  radio_checked: {},
  radio_disabled: {},
  radio_colorPrimary: {},
  radio_colorSecondary: {},
};

export const RadioGroup = {
  formControl_root: {},
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  radioGroup_root: {},
  formHelper_root: {},
  formHelper_dense: {},
  formHelper_error: {},
  formHelper_disabled: {},
};

export const Select = {
  formControl_root: {},
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  formHelper_root: {},
  formHelper_dense: {},
  formHelper_error: {},
  formHelper_disabled: {},
  select_root: {},
  select_select: {},
  select_selectMenu: {},
  select_disabled: {},
  select_icon: {},
  inputLabel_root: {},
  inputLabel_formControl: {},
  inputLabel_shrink: {},
  inputLabel_animated: {},
  inputLabel_marginDense: {},
  input_root: {},
  input_formControl: {},
  input_focused: {},
  input_disabled: {},
  input_underline: {},
  input_error: {},
  input_multiline: {},
  input_fullWidth: {},
  input_input: {},
  input_inputMarginDense: {},
  input_inputMultiline: {},
  input_inputType: {},
  input_inputTypeSearch: {},
  menu_paper: {},
  menuList_root: {},
  menuList_padding: {},
  menuList_dense: {},
  menuList_subheader: {},
};

export const TextField = {
  formControl_root: {},
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  inputLabel_root: {},
  inputLabel_formControl: {},
  inputLabel_shrink: {},
  inputLabel_animated: {},
  inputLabel_marginDense: {},
  input_root: {},
  input_formControl: {},
  input_focused: {},
  input_disabled: {},
  input_underline: {},
  input_error: {},
  input_multiline: {},
  input_fullWidth: {},
  input_input: {},
  input_inputMarginDense: {},
  input_inputMultiline: {},
  input_inputType: {},
  input_inputTypeSearch: {},
  formHelper_root: {},
  formHelper_dense: {},
  formHelper_error: {},
  formHelper_disabled: {},
};
