// For Example:
// export const styles = theme => ({
//   formControl_root: {},
//   formControl_marginNormal: {},
//   formControl_marginDense: {},
//   formControl_fullWidth: {},
//   formHelper_root: {},
//   formHelper_dense: {},
//   formHelper_error: {},
//   formHelper_disabled: {},
//   select_root: {},
//   select_select: {},
//   select_selectMenu: {},
//   select_disabled: {},
//   select_icon: {},
//   inputLabel_root: {},
//   inputLabel_formControl: {},
//   inputLabel_shrink: {},
//   inputLabel_animated: {},
//   inputLabel_marginDense: {},
//   input_root: {},
//   input_formControl: {},
//   input_focused: {},
//   input_disabled: {},
//   input_underline: {},
//   input_error: {},
//   input_multiline: {},
//   input_fullWidth: {},
//   input_input: {},
//   input_inputMarginDense: {},
//   input_inputMultiline: {},
//   input_inputType: {},
//   input_inputTypeSearch: {},
//   menu_paper: {},
//   menuList_root: {},
//   menuList_padding: {},
//   menuList_dense: {},
//   menuList_subheader: {},
// });

/** bootstrap風 */
const styles = theme => ({
  formControl_root: {
    margin: theme.spacing.unit,
    minWidth: 120,
  },
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  formHelper_root: {
    paddingLeft: '6px',
  },
  formHelper_dense: {},
  formHelper_error: {
    fontSize: '0.85rem',
    marginTop: '0px',
    marginLeft: theme.spacing.unit,
  },
  formHelper_disabled: {},
  select_root: {
    border: '1px solid #ced4da',
    borderRadius: 4,
    backgroundColor: theme.palette.common.white,
  },
  select_select: {
    paddingLeft: '6px',
    paddingTop: '6px',
    paddingBottom: '6px',
    width: 'calc(100% - 38px)',
    '&:focus': {
      backgroundColor: theme.palette.common.white,
    },
  },
  select_selectMenu: {},
  select_disabled: {},
  select_icon: {},
  inputLabel_root: {
    fontSize: 20,
    paddingLeft: '6px',
  },
  inputLabel_formControl: {},
  inputLabel_shrink: {},
  inputLabel_animated: {},
  inputLabel_marginDense: {},
  input_root: {
    padding: 0,
    'label + &': {
      marginTop: theme.spacing.unit * 3,
    },
  },
  input_formControl: {},
  input_focused: {},
  input_disabled: {},
  input_underline: {},
  input_error: {},
  input_multiline: {},
  input_fullWidth: {},
  input_input: {
    '&:focus': {
      borderRadius: 4,
      borderColor: '#80bdff',
      boxShadow: '0 0 0 0.2rem rgba(0,123,255,.25)',
    },
  },
  input_inputMarginDense: {},
  input_inputMultiline: {},
  input_inputType: {},
  input_inputTypeSearch: {},
  menu_paper: {},
  menuList_root: {
    padding: '0px',
  },
  menuList_padding: {},
  menuList_dense: {},
  menuList_subheader: {},
});

export default styles;
