// For Example:
// export const styles = theme => ({
//   formControl_root: {},
//   formControl_marginNormal: {},
//   formControl_marginDense: {},
//   formControl_fullWidth: {},
//   inputLabel_root: {},
//   inputLabel_formControl: {},
//   inputLabel_shrink: {},
//   inputLabel_animated: {},
//   inputLabel_marginDense: {},
//   input_root: {},
//   input_formControl: {},
//   input_focused: {},
//   input_disabled: {},
//   input_underline: {},
//   input_error: {},
//   input_multiline: {},
//   input_fullWidth: {},
//   input_input: {},
//   input_inputMarginDense: {},
//   input_inputMultiline: {},
//   input_inputType: {},
//   input_inputTypeSearch: {},
//   formHelper_root: {},
//   formHelper_dense: {},
//   formHelper_error: {},
//   formHelper_disabled: {},
// });

/** Bootstrap風 */
const styles = theme => ({
  formControl_root: {
    margin: theme.spacing.unit,
    flexDirection: 'row',
    alignItems: 'center',
  },
  formControl_marginNormal: {},
  formControl_marginDense: {},
  formControl_fullWidth: {},
  inputLabel_root: {
    fontSize: 20,
    paddingLeft: theme.spacing.unit * 1.5,
  },
  inputLabel_formControl: {},
  inputLabel_shrink: {},
  inputLabel_animated: {},
  inputLabel_marginDense: {},
  input_root: {
    padding: 0,
    'label + &': {
      marginTop: theme.spacing.unit * 3,
    },
  },
  input_formControl: {},
  input_focused: {},
  input_disabled: {},
  input_underline: {},
  input_error: {},
  input_multiline: {},
  input_fullWidth: {},
  input_input: {
    borderRadius: 4,
    backgroundColor: theme.palette.common.white,
    border: '1px solid #ced4da',
    fontSize: 16,
    padding: '5px 6px',
    width: 'calc(100% - 24px)',
    transition: theme.transitions.create(['border-color', 'box-shadow']),
    '&:focus': {
      borderColor: '#80bdff',
      boxShadow: '0 0 0 0.2rem rgba(0,123,255,.25)',
    },
  },
  input_inputMarginDense: {},
  input_inputMultiline: {},
  input_inputType: {},
  input_inputTypeSearch: {},
  formHelper_root: {
  },
  formHelper_dense: {},
  formHelper_error: {
    fontSize: '0.85rem',
    marginTop: '0px',
    marginLeft: theme.spacing.unit,
    paddingLeft: theme.spacing.unit,
  },
  formHelper_disabled: {},
});

export default styles;
